# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'macOS-latest'

variables:
  ${{ if not(eq(variables['Build.SourceBranchName'], 'master')) }}:
    group: 'DEV'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    group: 'PROD'

steps:
- script: |
    echo ${{variables.group}}
    echo $(SPLIT_THAT_BILL_BASEURL)
    echo $(SPLIT_THAT_BILL_AUTH_AUDIENCE)
    echo $(SPLIT_THAT_BILL_AUTH_DOMAIN)
  displayName: 'check variables'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'install Node.js'
- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'install'
# - script: |
#     npm run coverage
#   displayName: 'run coverage'
- script: |
    npm run build:prod
  displayName: 'build production'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist/splitthatbill'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/published_client/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/published_client'
    ArtifactName: 'drop'
    publishLocation: 'Container'
